######## ENVIRONMENT ########


######## THIS COMPOSE FILE ########
# - VirtualPrivateServer (vps01) -  Debian 12
# - Prefix/suffix "vps01" refers to the above host
# - Docker version 24.0.7, build afdd53b
# - Docker Compose version v2.21.0

######## NETWORKS ########
# You may customize the network subnets (10.x.x.0/24) below.
networks:
  default: # Default network docker 172.17.0.0/16
    driver: bridge 
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
  # t2_proxy:
  #   name: t2_proxy
  #   driver: bridge
  #   ipam:
  #     config:
  #       - subnet: 10.30.10.0/24
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 10.30.10.0/24

######## SECRETS ########
secrets:
  basic_auth_credentials:
    file: $SECRETSDIR/basic_auth_credentials
  cf_dns_api_token:
    file: $SECRETSDIR/cf_dns_api_token
  traefik_forward_auth:
    file: $SECRETSDIR/traefik_forward_auth
  mysql_root_password:
    file: $SECRETSDIR/mysql_root_password
  postgres_password:
    file: $SECRETSDIR/postgres_root_password
  pgadmin_password:
    file: $SECRETSDIR/pgadmin_password
  authelia_jwt_secret:
    file: $SECRETSDIR/authelia_jwt_secret
  authelia_session_secret:
    file: $SECRETSDIR/authelia_session_secret
  # authelia_storage_mysql_password:
  #   file: $SECRETSDIR/authelia_storage_mysql_password
  # authelia_notifier_smtp_password:
  #   file: $SECRETSDIR/authelia_notifier_smtp_password
  # authelia_duo_api_secret_key:
  #   file: $SECRETSDIR/authelia_duo_api_secret_key
  authelia_storage_encryption_key:
    file: $SECRETSDIR/authelia_storage_encryption_key
  guac_db_name:
    file: $SECRETSDIR/guac_db_name
  guac_mysql_user:
    file: $SECRETSDIR/guac_mysql_user
  guac_mysql_password:
    file: $SECRETSDIR/guac_mysql_password
  vnc_password:
    file: $SECRETSDIR/vnc_password
  vaultwarden_admin_token:
    file: $SECRETSDIR/vaultwarden_admin_token
  commafeed_db_password:
    file: $SECRETSDIR/commafeed_db_password
  nextcloud_admin_password:
    file: $SECRETSDIR/nextcloud_admin_password # put admin password in this file
  nextcloud_admin_user:
    file: $SECRETSDIR/nextcloud_admin_user # put admin username in this file
  nextcloud_apostgres_db:
    file: $SECRETSDIR/nextcloud_apostgres_db # put postgresql db name in this file
  nextcloud_apostgres_password:
    file: $SECRETSDIR/nextcloud_apostgres_password # put postgresql password in this file
  nextcloud_apostgres_user:
    file: $SECRETSDIR/nextcloud_apostgres_user # put postgresql username in this file
  odoo_postgres_password:
    file: $SECRETSDIR/odoo_postgres_password # put postgresql password in this file
  odoo_password:
    file: $SECRETSDIR/odoo_password # put odoo password in this file
include:
  ######## SERVICES ########
  # PREFIX - vps01
  # HOSTNAME=vps01 - defined in .env

  ################################
  ######## CORE ########
  ################################
  - compose/$HOSTNAME/socket-proxy.yml
  - compose/$HOSTNAME/traefik.yml
  - compose/$HOSTNAME/cloudflare-ddns.yml
  #- compose/$HOSTNAME/tailscale.yml
  #- compose/$HOSTNAME/oauth.yml
  #- compose/$HOSTNAME/authelia.yml
  #- compose/$HOSTNAME/portainer.yml
  #- compose/$HOSTNAME/dockge.yml

  ################################
  ######## DATABASES ########
  ################################
  #- compose/$HOSTNAME/prometheus.yml
  - compose/$HOSTNAME/mariadb.yml
  #- compose/$HOSTNAME/influxdb.yml
  - compose/$HOSTNAME/postgres.yml
  #- compose/$HOSTNAME/pgadmin.yml
  #- compose/$HOSTNAME/metabase.yml
  #- compose/$HOSTNAME/umami.yml
  #- compose/$HOSTNAME/redis.yml
  #- compose/$HOSTNAME/redis-commander.yml
  #- compose/$HOSTNAME/cloudbeaver.yml
  #- compose/$HOSTNAME/phpmyadmin.yml


  ################################
  ######## SECURITY ########
  ################################
  #- compose/$HOSTNAME/crowdsec.yml
  #- compose/$HOSTNAME/traefik-bouncer.yml
  #- compose/$HOSTNAME/adguardhome.yml

  ################################
  ######## WEBSERVER ########
  ################################
  #- compose/$HOSTNAME/caddy.yml
  #- compose/$HOSTNAME/php.yml

  ################################
  ######## OPERATING SYSTEMS ########
  ################################
  #- compose/$HOSTNAME/ubuntu.yml
  #- compose/$HOSTNAME/kali-linux.yml

  ################################
  ######## FRONTEND ########
  ################################
  #- compose/$HOSTNAME/autoindex.yml
  - compose/$HOSTNAME/homepage.yml
  #- compose/$HOSTNAME/sitespeed.yml
  #- compose/$HOSTNAME/whoami.yml
  #- compose/$HOSTNAME/homarr.yml
  #- compose/$HOSTNAME/dashy.yml


  ################################
  ########## OFFICE ##########
  ################################
  #- compose/$HOSTNAME/nextcloud.yml
  #- compose/$HOSTNAME/vaultwarden.yml
  #- compose/$HOSTNAME/odoo.yml
  #- compose/$HOSTNAME/obsidian.yml
  #- compose/$HOSTNAME/openwebui.yml
  #- compose/$HOSTNAME/mattermost.yml
  #- compose/$HOSTNAME/dockermailserver.yml

  ########## PERSONAL FINANCE ##########
  #- compose/$HOSTNAME/actual-server.yml
  #- compose/$HOSTNAME/firefly.yml
  #- compose/$HOSTNAME/maybe.yml



  ################################
  ######## MONITORING ########
  ################################
  #- compose/$HOSTNAME/beszel-hub.yml
  #- compose/$HOSTNAME/beszel-agent.yml
  #- compose/$HOSTNAME/grafana.yml
  #- compose/$HOSTNAME/uptime-kuma.yml
  #- compose/$HOSTNAME/dozzle.yml
  #- compose/$HOSTNAME/radarr-exporter.yml
  #- compose/$HOSTNAME/sonarr-exporter.yml
  #- compose/$HOSTNAME/lidarr-exporter.yml
  #- compose/$HOSTNAME/prowlarr-exporter.yml
  #- compose/$HOSTNAME/sabnzbd-exporter.yml
  #- compose/$HOSTNAME/node-exporter.yml
  #- compose/$HOSTNAME/checkmk.yml

  ################################
  ######## ADMIN ########
  ################################
  #- compose/$HOSTNAME/guacamole.yml
  #- compose/$HOSTNAME/kasm.yml

  ################################
  ######## UTILITIES ########
  ################################
  #- compose/$HOSTNAME/homeassistant.yml
  #- compose/$HOSTNAME/it-tools.yml
  #- compose/$HOSTNAME/isponsorblocktv.yml
  #- compose/$HOSTNAME/firefox.yml
  #- compose/$HOSTNAME/firefly.yml
  #- compose/$HOSTNAME/vscode.yml
  #- compose/$HOSTNAME/makemkv.yml
  #- compose/$HOSTNAME/mkvtoolnix.yml
  #- compose/$HOSTNAME/metube.yml
  #- compose/$HOSTNAME/semaphore.yml
  #- compose/$HOSTNAME/filebrowser.yml
  #- compose/$HOSTNAME/pwpush.yml
  #- compose/$HOSTNAME/rustdesk.yml

  ################################
  ######## NETWORK ########
  ################################
  #- compose/$HOSTNAME/gluetun.yml
  #- compose/$HOSTNAME/unifi.yml

  ################################
  ######## MAINTENANCE ########
  ################################
  #- compose/$HOSTNAME/docker-gc.yml
  #- compose/$HOSTNAME/deunhealth.yml


  ################################
  ######## DOWNLOADERS ########
  ################################
  #- compose/$HOSTNAME/jdownloader.yml
  #- compose/$HOSTNAME/qbittorrent.yml
  #- compose/$HOSTNAME/qbittorrent-vpn.yml
  #- compose/$HOSTNAME/sabnzbd.yml

  ################################
  ######## MEDIA MANAGEMENT - ARR SUITE ########
  ################################
  #- compose/$HOSTNAME/sonarr.yml
  #- compose/$HOSTNAME/radarr.yml
  #- compose/$HOSTNAME/lidarr.yml
  #- compose/$HOSTNAME/prowlarr.yml
  #- compose/$HOSTNAME/notifiarr.yml
  #- compose/$HOSTNAME/bazarr.yml
  #- compose/$HOSTNAME/flaresolverr.yml
  #- compose/$HOSTNAME/recyclarr.yml
  #- compose/$HOSTNAME/jellyseerr.yml
  #- compose/$HOSTNAME/overseerr.yml

  ################################
  ######## MEDIA SERVERS ########
  ################################
  #- compose/$HOSTNAME/jellyfin.yml
  #- compose/$HOSTNAME/airsonic-advanced.yml
  #- compose/$HOSTNAME/plex.yml
  #- compose/$HOSTNAME/tautulli.yml
  #- compose/$HOSTNAME/overseerr.yml
  #- compose/$HOSTNAME/plex-meta-manager.yml
  #- compose/$HOSTNAME/plex-image-cleanup.yml
  #- compose/$HOSTNAME/jellyfin-vue.yml

  ################################
  ######## BOOKS AND NEWS ########
  ################################
  #- compose/$HOSTNAME/calibre.yml
  #- compose/$HOSTNAME/commafeed.yml
  #- compose/$HOSTNAME/calibre-web.yml

  ################################
  ######## COMPLEMENTARY APPS ########
  ################################
  #- compose/$HOSTNAME/picard.yml
  #- compose/$HOSTNAME/recipya.yml
  #- compose/$HOSTNAME/tamari.yml
  #- compose/$HOSTNAME/grocy.yml


  ################################
  ######## OBSOLETE ########
  ################################
  #- compose/$HOSTNAME/obsolete/scrutiny.yml