# actual Your Finances — made simple https://actualbudget.org/
services:
  actual:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
    ports:
      - 5006:5006
    #profiles: ["apps", "all"]
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      # - ACTUAL_HTTPS_KEY=/data/selfhost.key
      # - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      # - ACTUAL_PORT=5006
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
    volumes:
      - $DOCKERDIR/appdata/actual/data:/data
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.actual-rtr.entrypoints=websecure"
      - "traefik.http.routers.actual-rtr.rule=Host(`actual.$DOMAINNAME_00`)"
      # Middlewares
      # - "traefik.http.routers.actual-rtr.middlewares=chain-no-auth@file" # For No Authentication
      - "traefik.http.routers.actual-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.actual-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.actual-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.actual-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.actual-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.actual-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.actual-rtr.service=actual-svc"
      - "traefik.http.services.actual-svc.loadbalancer.server.port=5006"
