services:
    adguardhome:
        image: adguard/adguardhome
        container_name: adguardhome
        hostname: adguardhome
        restart: unless-stopped
        networks:
            - socket_proxy
            - t3_proxy
        ports:
            - 5443:5443/udp
            - 5443:5443/tcp
            - 8853:8853/udp
            - 853:853/udp
            - 784:784/udp
            - 853:853/tcp
            - 3000:3000/tcp
            - 443:443/udp
            - 443:443/tcp
            - 80:80/tcp
            - 68:68/udp
            - 67:67/udp
            - 53:53/udp
            - 53:53/tcp
        volumes:
            - $DOCKERDIR/appdata/adguardhome/config:/opt/adguardhome/conf
            - $DOCKERDIR/appdata/adguardhome/:/opt/adguardhome/work
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=t3_proxy"      
             # HTTP Routers
            - "traefik.http.routers.adguard.entrypoints=web"
            - "traefik.http.routers.adguard.rule=Host(`dns.$DOMAINNAME_00`)" # change with your own domain/sub domain
            - "traefik.http.routers.adguard.middlewares=https-redirect@file"
            - "traefik.http.routers.adguard-secure.entrypoints=websecure"
            - "traefik.http.routers.adguard-secure.rule=Host(`dns.$DOMAINNAME_00`)" # change with your own domain/sub domain
            - "traefik.http.routers.adguard-secure.tls=true"
            - "traefik.http.routers.adguard-secure.tls.certresolver=letsencrypt"
            - "traefik.http.routers.adguard-secure.service=adguard-secure"
              # TCP Routers
            - "traefik.tcp.routers.adguard-tls.rule=HostSNI(`dns.$DOMAINNAME_00`)" # change with your own domain/sub domain
            - "traefik.tcp.routers.adguard-tls.tls=true"
            - "traefik.tcp.routers.adguard-tls.entrypoints=dot"
            - "traefik.tcp.routers.adguard-tls.tls.certresolver=letsencrypt"
            - "traefik.tcp.routers.adguard-tls.service=adguard-tls"
              # HTTP Services
            - "traefik.http.services.adguard-secure.loadbalancer.server.port=3000" # 3000 Change to 80 after first reboot and settings admin account
              # TCP Services
            - "traefik.tcp.services.adguard-tls.loadbalancer.server.port=53"
              # Middlewares
            # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth@file" # For No Authentication
            - "traefik.http.routers.traefik-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
            # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth-no-crowdsec@file"
            # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth-webos@file"
            # - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth-external@file"
            # - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth@file" # For Google OAuth
            # - "traefik.http.routers.traefik-rtr.middlewares=chain-authelia@file" # For Authelia Authentication