services:
  # Autoindex - Simple Directory Index
  autoindex:
    container_name: autoindex
    image: dceoy/nginx-autoindex:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #profiles: ["apps", "all"]
    networks:
      - t3_proxy
    # ports:
    #   - "$AUTOINDEX_PORT:80"
    volumes:
      #- $USERDIR:/var/lib/nginx/html:ro # Location you want to index
      - $EXTDRIVE:/var/lib/nginx/html:ro # Location you want to index
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.autoindex-rtr.entrypoints=websecure"
      - "traefik.http.routers.autoindex-rtr.rule=Host(`index.$DOMAINNAME_00`)"
      # Middlewares
      # - "traefik.http.routers.autoindex-rtr.middlewares=chain-no-auth@file" # For No Authentication
      - "traefik.http.routers.autoindex-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.autoindex-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.autoindex-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.autoindex-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.autoindex-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.autoindex-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.autoindex-rtr.service=autoindex-svc"
      - "traefik.http.services.autoindex-svc.loadbalancer.server.port=80"
