# IMPORTANT
# This configuration should work out of the box, but you must follow these steps when adding the system in the web UI:
# Update the KEY value with your public key, then run docker compose again to restart the agent.
# Use /beszel_socket/beszel.sock as the Host / IP.


services:
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    networks:
      - socket_proxy
      - default
    network_mode: host
    volumes:
      - $DOCKERDIR/appdata/beszel/socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      ######## monitoring extra folders - Mount a folder from the target filesystem in the container's /extra-filesystems directory
      #- /mnt/multimedia/.beszel:/extra-filesystems/multimedia:ro
      #- /mnt/download/.beszel:/extra-filesystems/download:ro
      - $BACKUP_DIR/.beszel:/extra-filesystems/backup_dir:ro
      - $LOG_DIR/.beszel:/extra-filesystems/log_dir:ro
      - $DOWNLOADSDIR/.beszel:/extra-filesystems/downloads_dir:ro
      - $MEDIA_DIR/.beszel:/extra-filesystems/media_dir:ro
      - $TEMP_DIR/.beszel:/extra-filesystems/temp_dir:ro
      - $BOOKS_DIR/.beszel:/extra-filesystems/books_dir:ro
      - $FOTOVIDEO_DIR/.beszel:/extra-filesystems/fotovideo_dir:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      # Do not remove quotes around the key
      KEY: '$BESZELPUBLICKEY'
      #DOCKER_HOST: tcp://socket-proxy:2375
      #LISTEN: 45876
