services:
  # calibre - Simple Directory Index
  calibre:
    container_name: calibre
    image: lscr.io/linuxserver/calibre-web:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #profiles: ["apps", "all"]
    networks:
      - t3_proxy
    ports:
      - 58083:8083
    volumes:
      - $DOCKERDIR/appdata/calibre/data:/config
      - $BOOKS_DIR:/books
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.calibre-rtr.entrypoints=websecure"
      - "traefik.http.routers.calibre-rtr.rule=Host(`calibre.$DOMAINNAME_00`)"
      # Middlewares
      # - "traefik.http.routers.calibre-rtr.middlewares=chain-no-auth@file" # For No Authentication
      - "traefik.http.routers.calibre-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.calibre-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.calibre-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.calibre-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.calibre-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.calibre-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.calibre-rtr.service=calibre-svc"
      - "traefik.http.services.calibre-svc.loadbalancer.server.port=8083"
