services:
  # commafeed - admin admin
  commafeed:
    container_name: commafeed
    # image: athou/commafeed:latest-h2
    # image: athou/commafeed:latest-mysql #mysql
    image: athou/commafeed:latest-postgres #postgres
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #profiles: ["apps", "all"]
    networks:
      - t3_proxy
      - socket_proxy #mysql #postgres
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 8082:8082
    volumes:
      - $DOCKERDIR/appdata/commafeed/db:/commafeed/data
    environment:
      # - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://10.10.10.240/commafeed?autoReconnect=true&failOverReadOnly=false&maxReconnects=20&rewriteBatchedStatements=true&timezone=UTC #mysql
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://10.10.10.230:5432/commafeed #postgres
      - QUARKUS_DATASOURCE_USERNAME=commafeed #mysql #postgres
      - QUARKUS_DATASOURCE_PASSWORD=commafeed #mysql #postgres # /run/secrets/commafeed_db_password
    deploy:
      resources:
        limits:
          memory: 256M
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.commafeed-rtr.entrypoints=websecure"
      - "traefik.http.routers.commafeed-rtr.rule=Host(`feed.$DOMAINNAME_00`)"
      # Middlewares
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth@file" # For No Authentication
      - "traefik.http.routers.traefik-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.commafeed-rtr.service=commafeed-svc"
      - "traefik.http.services.commafeed-svc.loadbalancer.server.port=8082"
    secrets:
      - commafeed_db_password
