services:
  # Firefox - Web Broswer
  # VNC password not working - check
  firefox:
    image: jlesage/firefox:latest
    container_name: firefox
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined # October 15, 2020 https://github.com/jlesage/docker-firefox/blob/master/README.md#allowing-the-membarrier-system-call
    restart: unless-stopped
    #profiles: ["apps", "all"]
    networks:
      - t3_proxy
    # ports:
    #   - "$FIREFOX_PORT:5800"
    volumes:
      - $DOCKERDIR/appdata/firefox:/config
      - $DOWNLOADSDIR:/data/downloads
      - /dev/shm:/dev/shm
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      TZ: $TZ
      UMASK: 002
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
      VNC_PASSWD: /run/secrets/vnc_password
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.firefox-rtr.entrypoints=websecure"
      - "traefik.http.routers.firefox-rtr.rule=Host(`firefox.$DOMAINNAME_00`)"
      # Middlewares
      # - "traefik.http.routers.firefox-rtr.middlewares=chain-no-auth@file" # For No Authentication
      - "traefik.http.routers.firefox-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.firefox-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.firefox-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.firefox-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.firefox-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.firefox-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.firefox-rtr.service=firefox-svc"
      - "traefik.http.services.firefox-svc.loadbalancer.server.port=5800"
