services:
  # flaresolverr - cloudflare resolver
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #profiles: ["apps", "all"]
    networks:
      - t3_proxy
    ports:
      - "${PORT:-8191}:8191"
    volumes:
      - $DOCKERDIR/appdata/flaresolverr:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.flaresolverr-rtr.entrypoints=websecure"
      - "traefik.http.routers.flaresolverr-rtr.rule=Host(`flaresolverr.$DOMAINNAME_00`)"
      # Middlewares
      - "traefik.http.routers.flaresolverr-rtr.middlewares=chain-no-auth@file" # chain-oauth@file for oauth
      # HTTP Services
      - "traefik.http.routers.flaresolverr-rtr.service=flaresolverr-svc"
      - "traefik.http.services.flaresolverr-svc.loadbalancer.server.port=8191"