services:
  # homarr - Application Dashboard
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #profiles: ["apps", "all"]
    networks:
      - t3_proxy
      - socket_proxy
    ports:
      - "7575:7575"
    volumes:
      - $DOCKERDIR/appdata/homarr:/appdata
      - $DOCKER_HOST:/var/run/docker.sock
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      SECRET_ENCRYPTION_KEY: c673857e80c3a40f35a6097e7387f063366214aae644e76a3f27c655c91ecdff
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.homarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.homarr-rtr.rule=Host(`homarr.$DOMAINNAME_00`) || Host(`www.homarr.$DOMAINNAME_00`)"
      # Middlewares
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth@file" # For No Authentication
      - "traefik.http.routers.traefik-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.homarr-rtr.service=homarr-svc"
      - "traefik.http.services.homarr-svc.loadbalancer.server.port=7575"
