services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    privileged: true
    network_mode: host
    # networks:
    #   t3_proxy: # Uncomment if you want to use a specific network
    volumes:
      - $DOCKERDIR/appdata/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      DISABLE_JEMALLOC: true
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.homeassistant-rtr.entrypoints=websecure"
      - "traefik.http.routers.homeassistant-rtr.rule=Host(`homeassistant.$DOMAINNAME_00`)"
      # Middlewares
      # - "traefik.http.routers.homeassistant-rtr.middlewares=chain-no-auth@file" # For No Authentication
      - "traefik.http.routers.homeassistant-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.homeassistant-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.homeassistant-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.homeassistant-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.homeassistant-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.homeassistant-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.homeassistant-rtr.service=homeassistant-svc"
      - "traefik.http.services.homeassistant-svc.loadbalancer.server.port=8123"
