services:
  # Homepage - Application Dashboard
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #profiles: ["apps", "all"]
    networks:
      - t3_proxy
      - socket_proxy
    # ports:
    #  - "$HOMEPAGE_PORT:3000"
    volumes:
      - $DOCKERDIR/appdata/homepage:/app/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.homepage-rtr.entrypoints=websecure"
      - "traefik.http.routers.homepage-rtr.rule=Host(`$DOMAINNAME_00`) || Host(`www.$DOMAINNAME_00`)"
      # Middlewares
      # - "traefik.http.routers.homepage-rtr.middlewares=chain-no-auth@file" # For No Authentication
      - "traefik.http.routers.homepage-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.homepage-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.homepage-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.homepage-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.homepage-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.homepage-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.homepage-rtr.service=homepage-svc"
      - "traefik.http.services.homepage-svc.loadbalancer.server.port=3000"
