services:
  # isponsorblocktv - SponsorBlock for TV
  isponsorblocktv:
    container_name: isponsorblocktv
    image: ghcr.io/dmunozv04/isponsorblocktv
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #profiles: ["core", "all"]
    networks:
      - t3_proxy
      - socket_proxy
    volumes:
      - $DOCKERDIR/appdata/isponsorblocktv/data:/app/data
