services:
  # IT-Tools - Status Page & Monitoring Server
  it-tools:
    image: corentinth/it-tools
    container_name: it-tools
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #profiles: ["apps", "all"]
    networks:
      - t3_proxy
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.it-tools-rtr.entrypoints=websecure"
      - "traefik.http.routers.it-tools-rtr.rule=Host(`it-tools.$DOMAINNAME_00`)"
      # Middlewares
      # - "traefik.http.routers.it-tools-rtr.middlewares=chain-no-auth@file" # For No Authentication
      - "traefik.http.routers.it-tools-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.it-tools-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.it-tools-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.it-tools-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.it-tools-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.it-tools-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.it-tools-rtr.service=it-tools-svc"
      - "traefik.http.services.it-tools-svc.loadbalancer.server.port=80"
