services:
    mtl:
      image: swip3798/mail-to-telegram:latest
      restart: unless-stopped
      container_name: mail-to-telegram
      networks:
        - t3_proxy
        - socket_proxy
      ports:
        - 17333:17333 # Set to the wanted port
      environment:
        TELEGRAM_BOT_TOKEN: "00000000:dhwaiuhdiuwahiudhwaiu" # Set this to your own API Token
        # ASYNC_STD_THREAD_COUNT: "4" # Add if you want to change the thread count used by the mtl server
        # STANDARD_CHAT_ID: "123456789" # Add if you want a fallback chat_id if the id can't be extracted from the recipient email


