services:
  # MariaDB - MySQL Database
  # After starting container for first time dexec and mysqladmin -u root password <password>
  mariadb:
    container_name: mariadb
    image: lscr.io/linuxserver/mariadb
    networks:
      socket_proxy:
        ipv4_address: 10.10.10.230 # You can specify a static IP
      default:
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #profiles: ["dbs", "all"]
    ports:
      - "3306:3306"
    volumes:
      - $DOCKERDIR/appdata/mariadb/data:/config
      - $DOCKERDIR/appdata/mariadb/scripts:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_MULTIPLE_DATABASES=$MARIADB_MULTIPLE_DATABASES
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MARIADB_MYSQL_LOCALHOST_USER=1
    secrets:
      - mysql_root_password
