services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    networks:
      - t3_proxy
    ports:
      - "8081:8081"
    volumes:
      - $DOWNLOADSDIR:/downloads
    environment:
      - TZ=$TZ
      - UID=$PUID
      - GID=$PGID
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.metube-rtr.entrypoints=websecure"
      - "traefik.http.routers.metube-rtr.rule=Host(`metube.$DOMAINNAME_00`)"
      # Middlewares
      # - "traefik.http.routers.metube-rtr.middlewares=chain-no-auth@file" # For No Authentication
      - "traefik.http.routers.metube-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.metube-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.metube-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.metube-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.metube-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.metube-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.metube-rtr.service=metube-svc"
      - "traefik.http.services.metube-svc.loadbalancer.server.port=8081"