# open webui docker compose
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
    ports:
      - "52364:8080"
    volumes:
      - $DOCKERDIR/appdata/openwebui/data:/app/backend/data
      - $DOCKERDIR/appdata/openwebui/config:/app/backend/config
      - $DOCKERDIR/appdata/openwebui/logs:/app/backend/logs
      - $DOCKERDIR/appdata/openwebui/uploads:/app/backend/uploads
    environment:
      - ENV=production
      #- ENABLE_SIGNUP=True
      #- ENABLE_LOGIN_FORM=True
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.openwebui-rtr.entrypoints=websecure"
      - "traefik.http.routers.openwebui-rtr.rule=Host(`openwebui.$DOMAINNAME_00`)"
      # Middlewares
      # - "traefik.http.routers.openwebui-rtr.middlewares=chain-no-auth@file" # For No Authentication
      - "traefik.http.routers.openwebui-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.openwebui-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.openwebui-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.openwebui-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.openwebui-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.openwebui-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.openwebui-rtr.service=openwebui-svc"
      - "traefik.http.services.openwebui-svc.loadbalancer.server.port=8080"
