# overseerr using Docker.
services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
      - socket_proxy
    ports:
      - 5055:5055
    #profiles: ["apps", "all"]
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - LOG_LEVEL=debug # optional
    volumes:
      - $DOCKERDIR/appdata/overseerr/config:/app/config
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.overseerr-rtr.entrypoints=websecure"
      - "traefik.http.routers.overseerr-rtr.rule=Host(`overseerr.$DOMAINNAME_00`)"
      # Middlewares
      # - "traefik.http.routers.overseerr-rtr.middlewares=chain-no-auth@file" # For No Authentication
      - "traefik.http.routers.overseerr-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.overseerr-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.overseerr-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.overseerr-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.overseerr-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.overseerr-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.overseerr-rtr.service=overseerr-svc"
      - "traefik.http.services.overseerr-svc.loadbalancer.server.port=5055"
