services:
  # Picard - Music Library Tagging and Management
  picard:
    image: mikenye/picard:latest
    container_name: picard
    security_opt:
      - no-new-privileges:true
    restart: "no"
    #profiles: ["media", "all"]
    networks:
      - t3_proxy
    # ports:
    #   - "$PICARD_PORT:5800"
    volumes:
      - $MEDIA_DIR:/data:rw
      - $DOCKERDIR/appdata/picard:/config:rw
      - /dev/shm:/dev/shm
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      TZ: $TZ
      UMASK: 002
      DISPLAY_WIDTH: 1600
      DISPLAY_HEIGHT: 960
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.picard-rtr.entrypoints=websecure"
      - "traefik.http.routers.picard-rtr.rule=Host(`picard.$DOMAINNAME_00`)"
      # Middlewares
      - "traefik.http.routers.picard-rtr.middlewares=chain-no-auth@file" # chain-oauth@file for oauth
      # HTTP Services
      - "traefik.http.routers.picard-rtr.service=picard-svc"
      - "traefik.http.services.picard-svc.loadbalancer.server.port=5800"
