services:
  # Plex - Media Server
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    restart: "no"
    #profiles: ["media", "all"]
    devices:
      - /dev/dri:/dev/dri # for harware transcoding
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      #- "33400:33400/tcp"
    volumes:
      - $DOCKERDIR/appdata/plex:/config
      - $MEDIA_DIR:/data/multimedia
      - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    environment:
      TZ: $TZ
      HOSTNAME: "Plex"
      PLEX_CLAIM_FILE: /run/secrets/plex_claim
      PLEX_UID: $PUID
      PLEX_GID: $PGID
      ADVERTISE_IP: "http://$MEDIASERVER_IP:32400/,http://$TAILSCALE_IP:32400/,https://plex.$DOMAINNAME_00"
      ALLOWED_NETWORKS: $LOCAL_IPS,$TAILSCALE_IPS
    secrets:
      - plex_claim
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.plex-rtr.entrypoints=websecure"
      - "traefik.http.routers.plex-rtr.rule=Host(`plex.$DOMAINNAME_00`)"
      # Middlewares
      - "traefik.http.routers.plex-rtr.middlewares=chain-no-auth@file" # For No Authentication
      # - "traefik.http.routers.plex-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.plex-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.plex-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.plex-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.plex-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.plex-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.plex-rtr.service=plex-svc"
      - "traefik.http.services.plex-svc.loadbalancer.server.port=32400"
