services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    networks:
      socket_proxy:
        ipv4_address: 10.10.10.240 # You can specify a static IP
      #default:
      #t3_proxy:
    ports:
      - 5432:5432
    volumes:
      - $DOCKERDIR/appdata/postgres/data:/var/lib/postgresql/data
      - $DOCKERDIR/appdata/postgres/config:/etc/postgresql
      - $DOCKERDIR/appdata/postgres/backup:/backup
      - $DOCKERDIR/appdata/postgres/scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER:"$POSTGRES_USER"
      - POSTGRES_PASSWORD_FILE:"/run/secrets/postgres_root_password"
      - POSTGRES_DB:"$POSTGRES_DB"
      - POSTGRES_MULTIPLE_DATABASES:"$POSTGRES_MULTIPLE_DATABASES"
    #healthcheck:
      #test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      #interval: 10s
      #timeout: 5s
      #retries: 5
    deploy:
      resources:
        limits:
          #cpus: "2"
          memory: 2G
    secrets:
      - postgres_root_password
