# Prometheus - Database for sensor data
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - default
      - socket_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #profiles: ["dbs", "all"]
    ports:
      - "9090:9090"
    volumes:
      - $DOCKERDIR/appdata/prometheus/config:/etc/prometheus
      - $DOCKERDIR/appdata/prometheus/data:/prometheus
    user: $PUID:$PGID
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
