services:
  # qBittorrent - Torrent downloader
  # Needs trailing / if using PathPrefixStrip
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #profiles: ["apps", "downloads", "all"]
    network:
      - t3_proxy
    ports:
      - "8077:8080" # crowdsec is using port 8080
      - "$QBITTORRENT_PORT:6881" # torrenting port tcp
      - "$QBITTORRENT_PORT:6881/udp" # torrenting port udp
    volumes:
      - $DOCKERDIR/appdata/qbittorrent:/config
      - $TORRENTDOWNLOADDIR:/data/downloads # Ensure that downloads folder is set to /data/downloads in qBittorrent
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    # TORRENTING_PORT: $QBITTORRENT_PORT # torrenting udp and tcp port, replace 6881 with $QBITTORRENT_PORT in ports 
      UMASK_SET: 002 # 002 for group read/write
    #   UMASK_SET: 022 # 022 for public read-only
    #   UMASK_SET: 027 # 027 for group read-only
    #   UMASK_SET: 077 # 077 for private read-only
    #   UMASK_SET: 0777 # 0777 for public read/write
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.qbittorrent-rtr.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent-rtr.rule=Host(`qbittorrent.$DOMAINNAME_00`)"
      # Middlewares
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth@file" # For No Authentication
      - "traefik.http.routers.traefik-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc"
      - "traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8080"