services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    environment:
      - ALWAYS_USE_RELAY=$RUSTDESK_ALWAYS_USE_RELAY
    command: hbbs
    volumes:
      - $DOCKERDIR/appdata/rustdesk/hbbs/data:/root
    network_mode: "host"

    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - $DOCKERDIR/appdata/rustdesk/hbbr/data:/root
    network_mode: "host"
    restart: unless-stopped
