services:
  # Autoindex - Simple Directory Index (for Sitespeed.io Results)
  sitespeed:
    container_name: sitespeed
    image: dceoy/nginx-autoindex:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    #profiles: ["apps", "all"]
    networks:
      - t3_proxy
    volumes:
      - $CONFIGDIR/sitespeed:/var/lib/nginx/html:ro # Location you want to index
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.sitespeed-rtr.entrypoints=websecure"
      - "traefik.http.routers.sitespeed-rtr.rule=Host(`sitespeed.$DOMAINNAME_00`)"
      # Middlewares
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth@file" # For No Authentication
      - "traefik.http.routers.traefik-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.sitespeed-rtr.service=sitespeed-svc"
      - "traefik.http.services.sitespeed-svc.loadbalancer.server.port=80"
