services:
  #  Umami is a simple, fast, privacy-focused alternative to Google Analytics. It is a self-hosted web analytics solution that is easy to use and provides detailed insights into your website's performance.
  #  It is designed to be lightweight and fast, making it a great choice for those who want to track their website's performance without the bloat of other analytics solutions.
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t3_proxy
      - socket_proxy
    ports:
      - "57124:3000"
    volumes:
      - $DOCKERDIR/appdata/umami/data:/var/lib/postgresql/data
      - $DOCKERDIR/appdata/umami/config:/app/config # Config directory
      - $DOCKERDIR/appdata/umami/logs:/app/logs # Logs directory
      - $DOCKERDIR/appdata/umami/uploads:/app/uploads # Uploads directory
    environment:
      DATABASE_URL: postgresql://umami:umami@postgres:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: /run/secrets/umami_app_secret
      UMAMI_ADMIN_PASSWORD: /run/secrets/umami_admin_password
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    secrets:
      - umami_app_secret
      - umami_admin_password
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.umami-rtr.entrypoints=websecure"
      - "traefik.http.routers.umami-rtr.rule=Host(`umami.$DOMAINNAME_00`)"
      # Middlewares
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth@file" # For No Authentication
      - "traefik.http.routers.umami-rtr.middlewares=chain-basic-auth@file" # For Basic HTTP Authentication
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-no-auth-webos@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth-external@file"
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-oauth@file" # For Google OAuth
      # - "traefik.http.routers.traefik-rtr.middlewares=chain-authelia@file" # For Authelia Authentication
      # HTTP Services
      - "traefik.http.routers.umami-rtr.service=umami-svc"
      - "traefik.http.services.umami-svc.loadbalancer.server.port=3000"